# Generated by Django 4.1.4 on 2023-01-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Course_id',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Course_id',
            new_name='Course',
        ),
    ]
